### ISSUE TITLE
Does not detect any devices after upgrade to v0.4.1 [Ecomax 850i]

### ISSUE THREAD

**Issue by zASSAz** [denpamusic/homeassistant-plum-ecomax#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

![изображение](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/8055254/21e4518a-9041-4826-8479-2f8e23df1aec)

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [X] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [X] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### I'm seeing following log messages:

```shell
2023-12-17 12:35:33.284 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyplumio/helpers/event_manager.py", line 130, in dispatch
    return_value = await callback(value)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyplumio/devices/ecomax.py", line 213, in _handle_ecomax_parameters
    parameter.values = values
    ^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'values'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thank you for the feedback!

It seems like there is name collision between `circulation_pump` sensor [here](https://github.com/denpamusic/PyPlumIO/blob/69817c508dcfabad02930983be8b08eb551bf060/pyplumio/structures/outputs.py#L15) and `circulation_pump` parameter [here](https://github.com/denpamusic/PyPlumIO/blob/69817c508dcfabad02930983be8b08eb551bf060/pyplumio/structures/ecomax_parameters.py#L481). This will affect any device, which advertises circulation pump control.

I've pulled v0.4.1 release for now, as this is pretty easy to fix. I'll put it back in later today.

Sorry for the inconvenience!

**Comment by denpamusic** [comment]
This has now been fixed and test case has been added to prevent it from happening in the future.
Thanks for your help!
