### ISSUE TITLE
After update to 2026.8.0

### ISSUE THREAD

**Issue by genrihb** [denpamusic/homeassistant-plum-ecomax#306]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### I'm having the following issue:

Lost integration

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [ ] ecoMAX 8xx series
- [x] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [x] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### I'm seeing following log messages:

```shell
Эта ошибка возникла в пользовательской интеграции.

Регистратор: custom_components.plum_ecomax
Источник: config_entries.py:4187
Интеграция: Plum ecoMAX (документация, проблемы)
Зафиксировано первый раз: 22:36:48 (2 случая)
Зафиксировано последний раз: 22:38:09

Error occurred loading flow for integration plum_ecomax: cannot import name 'async_extract_referenced_entity_ids' from 'homeassistant.helpers.service' (/usr/src/homeassistant/homeassistant/helpers/service.py)
Эта ошибка возникла в пользовательской интеграции.

Регистратор: custom_components.plum_ecomax
Источник: config_entries.py:4187
Интеграция: Plum ecoMAX (документация, проблемы)
Зафиксировано первый раз: 21:57:43 (1 случай)
Зафиксировано последний раз: 21:57:43

Error occurred loading flow for integration plum_ecomax: cannot import name 'SelectedEntities' from 'homeassistant.helpers.service' (/usr/src/homeassistant/homeassistant/helpers/service.py)
```

### My diagnostics data:

Return version 2026.7.4

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Please install the latest version v0.5.0 to fix this issue. Thanks!
